### PR TITLE
Add first plugins

### PR DESCRIPTION
**Pull request by Boernsman**

### CODE REVIEW

**Review by mzanetti — CHANGES_REQUESTED** [review]
Some minor comments only...  I don't have the possibility to test those plugins but code wise it's quite ok I think.

Now, we already have modbuscommand and drexelundweiss in the package repository. I suppose the separate code repos for those need to be deleted and removed from the CI when we add this. I've seen the changelog in this repository is copy of nymea-plugins' changelog when it was at 0.17. Please drop all the unrelated nymea-plugins history in there.

Now, for the versioning... Currently we have modbuscommander 0.1.5 (0.1.6 in experimental) in the repo and drexelundweiss version 0.0.5 (0.0.6 in experimental). So whatever you pick for the version for this plugins, it needs to be greater than 0.1.6 at least. I suppose it might make sense to sync those up with the nymea version as we do for nymea-plugins?

If I've overlooked any other possible conflicts with existing packages, please take care of those too.

**Comment by mzanetti** [comment]
I just wanted to add it to the CI pipeline but because I'd have to remove 2 other projects we'll have to wait for 0.23.1 to be out of the way.

**Comment by mzanetti** [comment]
Here's the preparation for the website update

https://github.com/nymea/nymea-docs/pull/85

**Comment by mzanetti** [comment]
Untagging, fails the build. Please re-tag after fixing.

```
dh_install --fail-missing
dh_install: Please use dh_missing --list-missing/--fail-missing instead
dh_install: This feature will be removed in compat 12.
dh_install: Cannot find (any matches for) "usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_deviceplugindrexelundweiss.so" (tried in ., debian/tmp)

dh_install: nymea-plugin-drexelundweiss missing files: usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_deviceplugindrexelundweiss.so
dh_install: Cannot find (any matches for) "usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_devicepluginmodbuscommander.so" (tried in ., debian/tmp)

dh_install: nymea-plugin-modbuscommander missing files: usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_devicepluginmodbuscommander.so
dh_install: Cannot find (any matches for) "usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_devicepluginmypv.so" (tried in ., debian/tmp)

dh_install: nymea-plugin-mypv missing files: usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_devicepluginmypv.so
dh_install: Cannot find (any matches for) "usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_devicepluginwallbe.so" (tried in ., debian/tmp)

dh_install: nymea-plugin-wallbe missing files: usr/lib/x86_64-linux-gnu/nymea/plugins/libnymea_devicepluginwallbe.so
dh_install: missing files, aborting
make[1]: *** [debian/rules:18: override_dh_install] Error 25
make[1]: Leaving directory '/home/ubuntu/nymea-plugins-modbus'
make: *** [debian/rules:11: binary] Error 2
```

**Comment by Boernsman** [comment]
> Some minor comments only... I don't have the possibility to test those plugins but code wise it's quite ok I think.
> 
> Now, we already have modbuscommand and drexelundweiss in the package repository. I suppose the separate code repos for those need to be deleted and removed from the CI when we add this. I've seen the changelog in this repository is copy of nymea-plugins' changelog when it was at 0.17. Please drop all the unrelated nymea-plugins history in there.
> 
> Now, for the versioning... Currently we have modbuscommander 0.1.5 (0.1.6 in experimental) in the repo and drexelundweiss version 0.0.5 (0.0.6 in experimental). So whatever you pick for the version for this plugins, it needs to be greater than 0.1.6 at least. I suppose it might make sense to sync those up with the nymea version as we do for nymea-plugins? So my suggestion would be to set it to 0.24.0 as that's the targeted release version for this.
> 
> If I've overlooked any other possible conflicts with existing packages, please take care of those too.

Resolved

**Review by mzanetti — APPROVED** [review]
:+1:

**Pull request merged**
